[[social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/yun7211"

  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "rss"
  name       = "RSS"
  url        = "/index.xml"

  [social.params]
    icon = "rss"
